"use client"
import "./globals.css";
import Header from "./components/layouts/Header";
import { MenuProvider } from "@/context/MenuContext";
import { AuthProvider } from "@/context/AuthProvider";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <MenuProvider>
            <header className="border-b sticky top-0 bg-white z-50">
              <Header/>
            </header>
            {children}
          </MenuProvider>
        </AuthProvider>
      </body>
    </html >
  );
}
