"use client"
import "./globals.css";
import Header from "./(components)/layouts/Header";
import { MenuProvider } from "@/context/MenuContext";
import { AuthProvider } from "@/context/AuthProvider";
import localFont from 'next/font/local'
import React from "react";
import TopBanner from "./(components)/layouts/topBanner";
// import { Playfair_Display } from 'next/font/google'

// export const metadata: Metadata = {x
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


// const playfair = Playfair_Display({
//   subsets: ['latin'],
//   display: 'swap',
// })

const zodiak = localFont({
  src: [
    {
      path: '../public/temp/fonts/Satoshi-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/temp/fonts/Satoshi-Bold.otf',
      weight: '900',
      style: 'bold',
    }
    ,
    {
      path: '../public/temp/fonts/Satoshi-BoldItalic.otf',
      weight: '900',
      style: 'italic',
    }

  ],
  variable: "--font-Zodiak"
})
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
      ${zodiak.variable}`}>
        <AuthProvider>
          <MenuProvider>
            <div className="m-4 sm:m-4 md:m-6 lg:m-6 xlg:m-6
      mt-2 sm:mt-2 md:mt-4 lg:mt-4 xlg:mt-4">
              <div className="text-center">
                <TopBanner />
              </div>
              <header className="sticky top-0 z-10 w-full bg-white">
                <div className="pt-4 bg-transparent">
                  <Header />
                </div>
              </header>
            </div>
            <div className="">
              {children}
            </div>
          </MenuProvider>
        </AuthProvider>
      </body>
    </html >
  );
}
